/*
 * PR Reviewer Assignment Service (Test Task, Fall 2025)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// принимает api_temas.go/teamaddpost

type Team struct {

	TeamName string `json:"team_name"`

	Members []TeamMember `json:"members"`
}
