/*
 * PR Reviewer Assignment Service (Test Task, Fall 2025)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PullRequestMergePostRequest struct {

	PullRequestId string `json:"pull_request_id"`
}
