/*
 * PR Reviewer Assignment Service (Test Task, Fall 2025)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

type PullRequest struct {

	PullRequestId string `json:"pull_request_id"`

	PullRequestName string `json:"pull_request_name"`

	AuthorId string `json:"author_id"`

	Status string `json:"status"`

	// user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string `json:"assigned_reviewers"`

	CreatedAt *time.Time `json:"createdAt,omitempty"`

	MergedAt *time.Time `json:"mergedAt,omitempty"`
}
