/*
 * PR Reviewer Assignment Service (Test Task, Fall 2025)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type TeamMember struct {

	UserId string `json:"user_id"`

	Username string `json:"username"`

	IsActive bool `json:"is_active"`
}
