/*
 * PR Reviewer Assignment Service (Test Task, Fall 2025)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/kgugunava/avito-tech-internship/internal/api/handlers"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the PullRequestsAPI part of the API
	PullRequestsAPI handlers.PullRequestsAPI
	// Routes for the TeamsAPI part of the API
	TeamsAPI handlers.TeamsAPI
	// Routes for the UsersAPI part of the API
	UsersAPI handlers.UsersAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"PullRequestCreatePost",
			http.MethodPost,
			"/pullRequest/create",
			handleFunctions.PullRequestsAPI.PullRequestCreatePost,
		},
		{
			"PullRequestMergePost",
			http.MethodPost,
			"/pullRequest/merge",
			handleFunctions.PullRequestsAPI.PullRequestMergePost,
		},
		{
			"PullRequestReassignPost",
			http.MethodPost,
			"/pullRequest/reassign",
			handleFunctions.PullRequestsAPI.PullRequestReassignPost,
		},
		{
			"TeamAddPost",
			http.MethodPost,
			"/team/add",
			handleFunctions.TeamsAPI.TeamAddPost,
		},
		{
			"TeamGetGet",
			http.MethodGet,
			"/team/get",
			handleFunctions.TeamsAPI.TeamGetGet,
		},
		{
			"UsersGetReviewGet",
			http.MethodGet,
			"/users/getReview",
			handleFunctions.UsersAPI.UsersGetReviewGet,
		},
		{
			"UsersSetIsActivePost",
			http.MethodPost,
			"/users/setIsActive",
			handleFunctions.UsersAPI.UsersSetIsActivePost,
		},
	}
}
