/*
 * PR Reviewer Assignment Service (Test Task, Fall 2025)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"github.com/gin-gonic/gin"

	"github.com/kgugunava/avito-tech-internship/internal/service"
	"github.com/kgugunava/avito-tech-internship/internal/api/models"
)

type PullRequestsAPI struct {
	pullRequestService *service.PullRequestService
}

func NewPullRequestAPI(pullRequestService *service.PullRequestService) *PullRequestsAPI {
	return &PullRequestsAPI{
		pullRequestService: pullRequestService,
	}
}

// Post /pullRequest/create
// Создать PR и автоматически назначить до 2 ревьюверов из команды автора 
func (api *PullRequestsAPI) PullRequestCreatePost(c *gin.Context) {
	var pullRequestCreatePostRequest models.PullRequestCreatePostRequest

	if err := c.ShouldBindJSON(&pullRequestCreatePostRequest); err != nil {
		c.JSON(500, models.ErrorResponse{
			Error: models.ErrorResponseError{
				Code: "INTERNAL_ERROR",
				Message: err.Error(),
			},
		})
		return
	}

	prResponse, errResponse := api.pullRequestService.Create(c.Request.Context(), pullRequestCreatePostRequest)

	if errResponse.Error.Code == "AUTHOR_NOT_FOUND" || errResponse.Error.Code == "TEAM_NOT_FOUND" {
		c.JSON(404, errResponse)
	}
	if errResponse.Error.Code == "PR_EXISTS" {
		c.JSON(409, errResponse)
	}

	c.JSON(201, models.PullRequestCreatePost201Response{
		Pr: prResponse,
	})
}

// Post /pullRequest/merge
// Пометить PR как MERGED (идемпотентная операция) 
func (api *PullRequestsAPI) PullRequestMergePost(c *gin.Context) {
	var pullRequestMergePostRequest models.PullRequestMergePostRequest

	if err := c.ShouldBindJSON(&pullRequestMergePostRequest); err != nil {
		c.JSON(500, models.ErrorResponse{
			Error: models.ErrorResponseError{
				Code: "INTERNAL_ERROR",
				Message: err.Error(),
			},
		})
	}

	prResponse, errResponse := api.pullRequestService.Merge(c.Request.Context(), pullRequestMergePostRequest)

	if errResponse.Error.Code == "NOT FOUND" {
		c.JSON(404, errResponse)
	}

	c.JSON(200, prResponse)
}

// Post /pullRequest/reassign
// Переназначить конкретного ревьювера на другого из его команды 
func (api *PullRequestsAPI) PullRequestReassignPost(c *gin.Context) {
	var pullRequestReassignPostRequest models.PullRequestReassignPostRequest

	if err := c.BindJSON(&pullRequestReassignPostRequest); err != nil {
		c.JSON(500, models.ErrorResponse{
			Error: models.ErrorResponseError{
				Code: "INTERNAL_ERROR",
				Message: err.Error(),
			},
		})
	}

	prResponse, errResponse, newReviewer := api.pullRequestService.Reassign(c.Request.Context(), pullRequestReassignPostRequest)

	if errResponse.Error.Code == "NOT_FOUND" {
		c.JSON(404, errResponse)
	}

	if errResponse.Error.Code == "PR_MERGED" || errResponse.Error.Code == "NOT_ASSIGNED" || errResponse.Error.Code == "NO_CANDIDATE" {
		c.JSON(409, errResponse)
	}

	c.JSON(200, models.PullRequestReassignPost200Response{
		Pr: prResponse,
		ReplacedBy: newReviewer,
	})
}

