/*
 * PR Reviewer Assignment Service (Test Task, Fall 2025)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"fmt"
	"log"

	"github.com/gin-gonic/gin"

	"github.com/kgugunava/avito-tech-internship/internal/api/models"
	"github.com/kgugunava/avito-tech-internship/internal/service"
)

type TeamsAPI struct {
	teamService *service.TeamService
}

func NewTeamsAPI(teamService *service.TeamService) *TeamsAPI {
	return &TeamsAPI{
		teamService: teamService,
	}
}

// Post /team/add
// Создать команду с участниками (создаёт/обновляет пользователей) 
func (api *TeamsAPI) TeamAddPost(c *gin.Context) {
	var team models.Team

	if err := c.ShouldBindJSON(&team); err != nil {
		c.JSON(500, models.ErrorResponse{
			Error: models.ErrorResponseError{
				Code: "INTERNAL_ERROR",
				Message: err.Error(),
			},
		})
		return
	}

	exists, err := api.teamService.IsTeamExists(c.Request.Context(), team.TeamName)
	if err != nil {
		log.Fatal("Error while checking if team exists: ", err)
		return
	}

	if exists {
		c.JSON(400, models.ErrorResponse{
			Error: models.ErrorResponseError{
				Code: "TEAM_EXISTS",
				Message: fmt.Sprintf("%s already exists", team.TeamName),
			},
		})
		return
	}

	createdTeam, err := api.teamService.CreateNewTeam(c.Request.Context(), team)
	if err != nil {
		c.JSON(500, models.ErrorResponse{
			Error: models.ErrorResponseError{
				Code:    "INTERNAL_ERROR",
				Message: err.Error(),
			},
		})
		return
	}

	c.JSON(201, models.TeamAddPost201Response{
		Team: createdTeam,
	})
}

// Get /team/get
// Получить команду с участниками 
func (api *TeamsAPI) TeamGetGet(c *gin.Context) {
	teamName := c.Query("team_name")
	if teamName == "" {
		c.JSON(400, models.ErrorResponse{
			Error: models.ErrorResponseError{
				Code:    "INVALID_REQUEST",
				Message: "team_name is required",
			},
		})
		return
	}

	// 2. Получаем команду из сервиса
	team, err := api.teamService.GetTeamByName(c.Request.Context(), teamName)
	if err != nil {
		c.JSON(404, models.ErrorResponse{
			Error: models.ErrorResponseError{
				Code:    "TEAM_NOT_FOUND",
				Message: fmt.Sprintf("team %s not found", teamName),
			},
		})
		return
	}
	
	c.JSON(200, team)
}

