/*
 * PR Reviewer Assignment Service (Test Task, Fall 2025)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"fmt"

	"github.com/gin-gonic/gin"

	"github.com/kgugunava/avito-tech-internship/internal/api/models"
	"github.com/kgugunava/avito-tech-internship/internal/service"
)

type UsersAPI struct {
	userService *service.UserService
}

func NewUserAPI(userService *service.UserService) *UsersAPI {
	return &UsersAPI{
		userService: userService,
	}
}

// Get /users/getReview
// Получить PR'ы, где пользователь назначен ревьювером 
func (api *UsersAPI) UsersGetReviewGet(c *gin.Context) {
	userId := c.Query("user_id")
	if userId == "" {
		c.JSON(400, models.ErrorResponse{
			Error: models.ErrorResponseError{
				Code: "INVALID_REQUEST",
				Message: "user_id is required",
			},
		})
		return
	}

	prsResponse, err := api.userService.GetReviews(c.Request.Context(), userId)
	
	if err.Error.Code == "USER_NOT_FOUND" {
		c.JSON(404, err)
	}

	if err.Error.Code == "INTERNAL_ERROR" {
		c.JSON(500, err)
	}

	c.JSON(200, models.UsersGetReviewGet200Response{
		UserId: userId,
		PullRequests: prsResponse.PullRequests,
	})
}

// Post /users/setIsActive
// Установить флаг активности пользователя 
func (api *UsersAPI) UsersSetIsActivePost(c *gin.Context) {
	var usersSetIsActiveRequest models.UsersSetIsActivePostRequest
	
	if err := c.ShouldBindJSON(&usersSetIsActiveRequest); err != nil {
		c.JSON(500, models.ErrorResponse{
			Error: models.ErrorResponseError{
				Code: "INTERNAL_ERROR",
				Message: err.Error(),
			},
		})
		return
	}

	user, err := api.userService.SetIsActivePost(c.Request.Context(), usersSetIsActiveRequest)
	if err != nil {
		c.JSON(404, models.ErrorResponse{
			Error: models.ErrorResponseError{
				Code: "USER_NOT_FOUND",
				Message: fmt.Sprint("user %s not found", usersSetIsActiveRequest.UserId),
			},
		})
	}

	c.JSON(200, models.UsersSetIsActivePost200Response{
		User: user,
	})
}

